// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMnwrqURIuhBaiT_DX_aICocURUkK9Td0',
    appId: '1:943341995509:web:8bd6ad086ee76239d04cbc',
    messagingSenderId: '943341995509',
    projectId: 'fir-tattle',
    authDomain: 'fir-tattle.firebaseapp.com',
    storageBucket: 'fir-tattle.appspot.com',
    measurementId: 'G-RXGEGRQY2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfrgr-lwxhemO5TbRQTjTG3vgfw0nmJmc',
    appId: '1:943341995509:android:5311b33c6ae1619ad04cbc',
    messagingSenderId: '943341995509',
    projectId: 'fir-tattle',
    storageBucket: 'fir-tattle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpRgyWGHI4FfQa_cfQ8url7OBQURJeRoE',
    appId: '1:943341995509:ios:55654b27571b672cd04cbc',
    messagingSenderId: '943341995509',
    projectId: 'fir-tattle',
    storageBucket: 'fir-tattle.appspot.com',
    iosClientId: '943341995509-opg1kib4197lfap248v49umma4rvm4sh.apps.googleusercontent.com',
    iosBundleId: 'com.fresho.tattle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpRgyWGHI4FfQa_cfQ8url7OBQURJeRoE',
    appId: '1:943341995509:ios:522a6c7b041871bfd04cbc',
    messagingSenderId: '943341995509',
    projectId: 'fir-tattle',
    storageBucket: 'fir-tattle.appspot.com',
    iosClientId: '943341995509-aqbb8ebd5gc56o6f0pvhjituqi24dj46.apps.googleusercontent.com',
    iosBundleId: 'com.fresho.tattle.RunnerTests',
  );
}
